version: "3.8"
services:
  postgres:
    image: postgres
    container_name: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mypgdbpass
    volumes:
      - postgres_data:/var/lib/postgresql/data

  yosai_server:
    container_name: yosai_server
    image: yosai-server:multi
    restart: always
    ports:
      - "8080:8080"
    environment:
      DB_PASS: mypgdbpass
      DB_USER: postgres
      DB_HOST: "192.168.50.35:5432"
    depends_on:
      - postgres

volumes:
  postgres_data:
  pgadmin_data:
