package keytags

const HASHICORP_VAULT_KEYNAME = "HASHICORP_VAULT_KEY"
const LINODE_API_KEYNAME = "LINODE_API_KEY"
const SERVER_ROOT_PASS_KEYNAME = "ROOT_USER"
const SERVER_SSH_KEY_KEYNAME = "ROOT_SSHKEY"
const SEMAPHORE_API_KEYNAME = "SEMAPHORE_API_KEY"
